using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static GH_Toolkit_Core.QB.QBConstants;

namespace GH_Toolkit_Core.Other
{
    public class ForbiddenChecksums
    {
        private static readonly HashSet<string> Gh3Checksums = new HashSet<string>
        {
            "anarchyintheuk",
            "avalancha",
            "barracuda",
            "beforeiforget",
            "bellyofashark",
            "blackmagicwoman",
            "blacksunshine",
            "bossslash",
            "bosstom",
            "bossdevil",
            "bullsonparade",
            "cantbesaved",
            "cherubrock",
            "citiesonflame",
            "cliffsofdover",
            "closer",
            "cultofpersonality",
            "dontholdback",
            "downndirty",
            "evenflow",
            "fcpremix",
            "generationrock",
            "gothatfar",
            "helicopter",
            "hitmewithyourbestshot",
            "hierkommtalex",
            "holidayincambodia",
            "imintheband",
            "impulse",
            "inlove",
            "koolthing",
            "knightsofcydonia",
            "lagrange",
            "laydown",
            "mauvaisgarcon",
            "metalheavylady",
            "minuscelsius",
            "mississippiqueen",
            "missmurder",
            "monsters",
            "mycurse",
            "mynameisjonas",
            "nothingformehere",
            "numberofthebeast",
            "one",
            "paintitblack",
            "paranoid",
            "prayeroftherefugee",
            "pridenjoy",
            "radiosong",
            "rainingblood",
            "reptilia",
            "rocknrollallnite",
            "rockulikeahurricane",
            "ruby",
            "sabotage",
            "sameoldsonganddance",
            "schoolsout",
            "shebangsadrum",
            "slowride",
            "stricken",
            "storyofmylife",
            "suckmykiss",
            "sunshineofyourlove",
            "talkdirtytome",
            "takethislife",
            "themetal",
            "theseeker",
            "thewayitends",
            "threesandsevens",
            "thrufireandflames",
            "welcometothejungle",
            "whenyouwereyoung",
            "synctest",
            "synctestplaytoaudio",
            "synctestaudioandvisual",
            "tutorial_1b",
            "tutorial_1c",
            "tutorial_1d",
            "tutorial_1e",
            "tutorial_2a",
            "tutorial_2b",
            "tutorial_2c",
            "tutorial_3a",
            "tutorial_3b",
            "tutorial_3c",
            "tutorial_3d",
            "tutorial_4c",
            "tutorial_4e",
            "dlc3",
            "dlc4",
            "dlc5",
            "dlc6",
            "dlc7",
            "dlc8",
            "dlc1",
            "dlc2",
            "dlc17",
            "dlc14",
            "dlc15",
            "dlc16",
            "dlc19",
            "dlc26",
            "dlc18",
            "dlc9",
            "dlc11",
            "dlc12",
            "dlc13",
            "dlc36",
            "dlc10",
            "dlc24",
            "dlc25",
            "dlc37",
            "dlc29",
            "dlc30",
            "dlc31",
            "dlc27",
            "dlc28",
            "dlc32",
            "dlc38",
            "dlc39",
            "dlc40",
            "dlc49",
            "dlc50",
            "dlc51",
            "dlc33",
            "dlc34",
            "dlc35",
            "dlc45",
            "dlc46",
            "dlc47",
            "dlc61",
            "dlc68",
            "dlc69",
            "dlc70",
            "dlc71",
            "dlc72",
            "dlc73",
            "dlc75",
            "dlc74",
            "dlc62",
            "dlc63",
            "dlc66",
            "dlc80",
            "dlc81",
            "dlc82",
            "dlc85",
            "dlc89",
            "dlc87",
            "dlc86",
            "dlc84",
            "dlc91",
            "dlc90",
            "dlc88",
            "dlc92",
            "dlc93",
            "dlc83"
        };

        private static readonly Dictionary<string, HashSet<string>> ForbiddenChecks = new Dictionary<string, HashSet<string>>
        {
            { GAME_GH3, Gh3Checksums }
        };

        public static HashSet<string> GetForbiddenChecksums(string game)
        {
            if (ForbiddenChecks.TryGetValue(game, out HashSet<string>? checksums))
            {
                return checksums;
            }
            return new HashSet<string>();
        }
    }
}